version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
    - "5433:5432"
    volumes:
    - /data/postgres:/data/postgres
    env_file:
    - docker.env
    networks:
    - postgres
 
  pgadmin:
    links:
    - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
    - "5435:80"
    volumes:
    - /data/pgadmin:/root/.pgadmin
    env_file:
    - docker.env
    networks:
    - postgres
    
  api:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on: 
      - postgres
    env_file: 
    - docker.env
    ports:
        - "3333:3000"
 
networks:
  postgres:
    driver: bridge